
package jp.co.techmatrix.store.services.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Search", targetNamespace = "http://impl.services.store.techmatrix.co.jp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Search {


    /**
     * 
     * @return
     *     returns java.util.List<jp.co.techmatrix.store.services.impl.Book>
     */
    @WebMethod
    @WebResult(name = "getAllItemReturn", targetNamespace = "")
    @RequestWrapper(localName = "getAllItemOperation", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetAllItemOperation")
    @ResponseWrapper(localName = "getAllItemOperationResponse", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetAllItemOperationResponse")
    @Action(input = "http://impl.services.store.techmatrix.co.jp/Search/getAllItemOperationRequest", output = "http://impl.services.store.techmatrix.co.jp/Search/getAllItemOperationResponse")
    public List<Book> getAllItemOperation();

    /**
     * 
     * @param getItemByIdRequest
     * @return
     *     returns jp.co.techmatrix.store.services.impl.Book
     */
    @WebMethod
    @WebResult(name = "getItemByIdReturn", targetNamespace = "")
    @RequestWrapper(localName = "getItemByIdOperation", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetItemByIdOperation")
    @ResponseWrapper(localName = "getItemByIdOperationResponse", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetItemByIdOperationResponse")
    @Action(input = "http://impl.services.store.techmatrix.co.jp/Search/getItemByIdOperationRequest", output = "http://impl.services.store.techmatrix.co.jp/Search/getItemByIdOperationResponse")
    public Book getItemByIdOperation(
        @WebParam(name = "getItemByIdRequest", targetNamespace = "")
        int getItemByIdRequest);

    /**
     * 
     * @param getItemByTitleRequest
     * @return
     *     returns java.util.List<jp.co.techmatrix.store.services.impl.Book>
     */
    @WebMethod
    @WebResult(name = "getItemByTitleReturn", targetNamespace = "")
    @RequestWrapper(localName = "getItemByTitleOperation", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetItemByTitleOperation")
    @ResponseWrapper(localName = "getItemByTitleOperationResponse", targetNamespace = "http://impl.services.store.techmatrix.co.jp/", className = "jp.co.techmatrix.store.services.impl.GetItemByTitleOperationResponse")
    @Action(input = "http://impl.services.store.techmatrix.co.jp/Search/getItemByTitleOperationRequest", output = "http://impl.services.store.techmatrix.co.jp/Search/getItemByTitleOperationResponse")
    public List<Book> getItemByTitleOperation(
        @WebParam(name = "getItemByTitleRequest", targetNamespace = "")
        String getItemByTitleRequest);

}
